apiVersion: apps/v1
kind: Deployment
metadata:
  name: &service-name dockerk8nginxsber #yaml anchors
  labels: &labels
    app: *service-name
spec:
  minReadySeconds: 1
  selector:
    matchLabels: *labels
  replicas: 1
  revisionHistoryLimit: 10
  template: 
    metadata:
      labels: *labels
    spec:
      containers:
      - name: *service-name
        image: ryazvenka/dockerk8nginxsber:v1
        command: ["/usr/sbin/nginx", "-g", "daemon off;"]
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
