apiVersion: v1
kind: Service
metadata:
  name: &service-name dockerk8nginxsber
spec:
  type: NodePort
  selector:
    app: *service-name
  ports:
    - name: http
      port: 80
      nodePort: 30080 # nodePort has to be in range 30000-32767
      protocol: TCP