FROM centos:centos8

LABEL maintainer="Ruslan Yazvenko"

#ENV proxy="http://proxyhost:8080" \
#    proxy_username="proxyname" \
#    proxy_password="proxypass"

RUN yum -y update && \
    yum -y install nginx &&\
    yum -y autoremove &&\
    yum clean all

COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /usr/share/nginx/html/index.html

#EXPOSE 80

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
#CMD ["nginx", "-g", "daemon off;"]
