---

- name: Display the config
  debug:
    msg: "Hostname =  {{ ansible_facts.hostname }}"
#    var: ansible_facts

- name: Run a shell command and register its output as a variable
  shell: psql --version
  register: command_result_1

- name: Show Value of command_result_1
  debug:
    var: command_result_1.stdout

- name: Run a shell command and register its output as a variable
  shell: psql --version
  register: command_result_2

- name: Show Value of command_result_2
  debug:
    var: command_result_2.stdout

- name: Show check result
  debug:
    msg: "Result Success ### {{ command_result_1.stdout }} = {{ command_result_2.stdout }}###"
  when: command_result_1.stdout == command_result_2.stdout
